# Generated by Django 4.1.2 on 2023-02-27 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_dep', models.BigAutoField(db_column='Id_dep', primary_key=True, serialize=False)),
                ('nom_dep', models.CharField(db_column='Nom_dep', max_length=100, unique=True, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_esp', models.BigAutoField(db_column='Id_esp', primary_key=True, serialize=False)),
                ('nom_esp', models.CharField(db_column='Especialidad', max_length=150, unique=True, verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_hiscli', models.BigAutoField(db_column='Id_hiscli', primary_key=True, serialize=False)),
                ('diag_hiscli', models.TextField(db_column='Id_diag', null=True, verbose_name='Diagnostico')),
            ],
            options={
                'verbose_name': 'Historia_clinica',
                'verbose_name_plural': 'Historias_clinicas',
            },
        ),
        migrations.CreateModel(
            name='RolPersona',
            fields=[
                ('id_rol', models.BigAutoField(db_column='Id_rol', primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(choices=[('Prof_salud', 'Profesional de la salud'), ('Familiar', 'Familiar'), ('Paciente', 'Paciente')], db_column='Nom_rol', max_length=100, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol_persona',
                'verbose_name_plural': 'Rol_personas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Signo_Vital',
            fields=[
                ('id_tipsig', models.BigAutoField(db_column='Id_tipsig', primary_key=True, serialize=False)),
                ('nom_tipsig', models.CharField(db_column='Nom_tipsig', max_length=150, verbose_name='Tipo De Signo Vital')),
            ],
            options={
                'verbose_name': 'Tipo_signo_vital',
                'verbose_name_plural': 'Tipos_signos_vitales',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_doc', models.AutoField(db_column='Id_doc', primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(db_column='Tipo_doc', max_length=150, unique=True, verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo_documento',
                'verbose_name_plural': 'Tipos_documentos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(db_column='Id_per', primary_key=True, serialize=False)),
                ('nom_per', models.CharField(db_column='Nombre', max_length=100, verbose_name='Nombres')),
                ('primerApe_per', models.CharField(db_column='Pri_apellido', max_length=100, verbose_name='Primer Apellido')),
                ('segundoApe_per', models.CharField(db_column='Seg_apellido', max_length=100, verbose_name='Segundo Apellido')),
                ('telefono', models.CharField(db_column='Teléfono', max_length=25, verbose_name='Teléfono')),
                ('numdoc_per', models.CharField(db_column='Numero_doc', max_length=25, unique=True, verbose_name='Número de documento')),
                ('gen_per', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], db_column='Género', max_length=1, verbose_name='Género')),
                ('password', models.CharField(db_column='Contraseña', max_length=256, verbose_name='Contraseña')),
                ('last_login', models.DateTimeField(db_column='Último Ingreso', null=True)),
                ('is_superuser', models.BooleanField(db_column='Superuser', default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_doc', models.ForeignKey(db_column='Id_doc', on_delete=django.db.models.deletion.CASCADE, to='AppHospEnCasa.tipodocumento', verbose_name='Id documento')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='FamiliarPaciente',
            fields=[
                ('id_fam', models.OneToOneField(db_column='Id_per', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('paren_fam', models.CharField(db_column='Paren_fam', max_length=20, null=True, verbose_name='Parentesco')),
                ('email_fam', models.EmailField(db_column='Email_fam', max_length=254, verbose_name='Correo Del Familiar')),
            ],
            options={
                'verbose_name': 'Familiar_paciente',
                'verbose_name_plural': 'Familiar_pacientes',
            },
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id_sug', models.BigAutoField(db_column='Id_sug', primary_key=True, serialize=False)),
                ('nom_sug', models.CharField(max_length=200, verbose_name='Sugerencia')),
                ('descript_sug', models.TextField(db_column='Descript_sug', verbose_name='Descripción De Sugerencia')),
                ('fecha_sug', models.DateTimeField(db_column='Fecha_sug', verbose_name='Fecha De Sugerencia')),
                ('id_hiscli', models.ForeignKey(db_column='id_hiscli', on_delete=django.db.models.deletion.CASCADE, to='AppHospEnCasa.historiaclinica', verbose_name='Historia Clínica')),
            ],
            options={
                'verbose_name': 'Sugerencias',
                'verbose_name_plural': 'Sugerencias',
            },
        ),
        migrations.CreateModel(
            name='Signo_Vital',
            fields=[
                ('id_sigvi', models.BigAutoField(db_column='Id_sigvi', primary_key=True, serialize=False)),
                ('medicion_sig', models.DecimalField(db_column='Medicion_sig', decimal_places=3, max_digits=3, verbose_name='Medición Del Signo Vital')),
                ('fecha_sig', models.DateTimeField(db_column='Fecha_sig', verbose_name='Fecha De Seguimiento')),
                ('id_hiscli', models.ForeignKey(db_column='Id_hiscli', on_delete=django.db.models.deletion.CASCADE, to='AppHospEnCasa.historiaclinica', verbose_name='Historia Clínica')),
                ('id_tipsig', models.ForeignKey(db_column='Id_tipsig', on_delete=django.db.models.deletion.CASCADE, to='AppHospEnCasa.tipo_signo_vital', verbose_name='Signo Vital')),
            ],
            options={
                'verbose_name': 'Signo_vital',
                'verbose_name_plural': 'Signos_vitales',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.BigAutoField(db_column='Id_ciudad', primary_key=True, serialize=False)),
                ('nom_ciudad', models.CharField(db_column='Nom_ciudad', max_length=100, verbose_name='Ciudad')),
                ('id_dep', models.ForeignKey(db_column='Id_dep', on_delete=django.db.models.deletion.CASCADE, related_name='Departamento', to='AppHospEnCasa.departamento')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Profesional_salud',
            fields=[
                ('id_pro', models.OneToOneField(db_column='Id_pro', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Profesional_salud', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tarj_pro', models.CharField(db_column='Tarj_pro', max_length=50, verbose_name='Tarjeta Profesional')),
                ('id_esp', models.ForeignKey(db_column='Id_esp', on_delete=django.db.models.deletion.CASCADE, to='AppHospEnCasa.especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Profesional_salud',
                'verbose_name_plural': 'Profesionales_salud',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_pac', models.OneToOneField(db_column='Id_pac', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Paciente', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fech_nac', models.DateField(db_column='Fech_nac', verbose_name='Fecha De Nacimiento')),
                ('rh_pac', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], db_column='Rh_pac', max_length=3, verbose_name='Grupo Sanguíneo')),
                ('dir_pac', models.CharField(db_column='Dir_pac', max_length=200, verbose_name='Direccion')),
                ('lon_pac', models.CharField(db_column='Lon_pac', default='Sin Registro', max_length=40, verbose_name='Longitud')),
                ('lat_pac', models.CharField(db_column='Lat_pac', default='Sin Registro', max_length=40, verbose_name='Latitud')),
                ('id_ciudad', models.ForeignKey(db_column='Id_ciudad', on_delete=django.db.models.deletion.CASCADE, to='AppHospEnCasa.ciudad', verbose_name='Ciudad')),
                ('id_fam', models.OneToOneField(db_column='Id_fam', on_delete=django.db.models.deletion.CASCADE, to='AppHospEnCasa.familiarpaciente', verbose_name='Familiar del paciente')),
                ('id_pro', models.ForeignKey(db_column='Id_pro', on_delete=django.db.models.deletion.CASCADE, to='AppHospEnCasa.profesional_salud', verbose_name='Profesional de la salud')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='id_pac',
            field=models.OneToOneField(db_column='Id_pac', on_delete=django.db.models.deletion.CASCADE, to='AppHospEnCasa.paciente', verbose_name='Paciente'),
        ),
    ]
