# Generated by Django 4.1.2 on 2023-02-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospEnCasa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='lat_pac',
            field=models.CharField(db_column='Lat_pac', default='Sin Registro', max_length=60, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='lon_pac',
            field=models.CharField(db_column='Lon_pac', default='Sin Registro', max_length=60, verbose_name='Longitud'),
        ),
    ]
